### ISSUE TITLE
Missing navigation docs

### ISSUE THREAD

**Issue by SudoerWithAnOpinion** [PeterGrace/meshtui#3]
When navigating in the application, changing tabs requires the use of TAB or SHIFT + TAB to navigate along the top bar; this is not documented in the application or in the repository.

**Comment by PeterGrace** [comment]
> When navigating in the application, changing tabs requires the use of TAB or SHIFT + TAB to navigate along the top bar; this is not documented in the application or in the repository.

I am planning on adding more help in-app, for instance if you hit F1 on the Nodes tab, it will explain what the fields mean -- I'm going to implement context-specific helps for each screen soon.  I'm also going to work on a docs website as well since its time.  In the meantime I'm going to put in some basic info in the README to help people get started.  Thanks for the issue!
